import {
  BagIcon,
  CameraIcon,
  CancelIcon,
  CellPhoneIcon,
  ComputerIcon,
  CustomerServiceIcon,
  DeliveryIcon,
  DollarIcon,
  GamepadIcon,
  HeadphoneIcon,
  LogoutIcon,
  MoneyBagIcon,
  ProfileIcon,
  SecureIcon,
  ShopIcon,
  ShoppingBagIcon,
  SmartWatchIcon,
  StarLineIcon,
} from "@/icons";

/* all default values */

/* nav bar data */
export const navItems = [
  { label: "Home", route: "/" },
  { label: "Contact", route: "/contact" },
  { label: "About", route: "/about" },
  { label: "Sign Up", route: "/sign-up" },
];

/* user dropdown data */
export const userDropdownData = [
  {
    _id: 1,
    label: "Manage My Account",
    route: "/user/profile",
    icon: ProfileIcon,
  },
  { _id: 2, label: "My Order", route: "/user/order", icon: BagIcon },
  {
    _id: 3,
    label: "My Cancellations",
    route: "/user/cancellations",
    icon: CancelIcon,
  },
  { _id: 4, label: "My Reviews", route: "/user/reviews", icon: StarLineIcon },
  // { _id: 5, label: "Logout", icon: LogoutIcon },
];

/* hero section data */
export const heroNavbarData = [
  {
    _id: 1,
    label: "Woman’s Fashion",
    link: "/womens-fashion",
    hasSubmenu: true,
    submenu: [
      { _id: 101, label: "Dresses", link: "/womens-fashion/dresses" },
      { _id: 102, label: "Tops", link: "/womens-fashion/tops" },
      { _id: 103, label: "Shoes", link: "/womens-fashion/shoes" },
      { _id: 104, label: "Bags", link: "/womens-fashion/bags" },
    ],
  },
  {
    _id: 2,
    label: "Men’s Fashion",
    link: "/mens-fashion",
    hasSubmenu: true,
    submenu: [
      { _id: 201, label: "Shirts", link: "/mens-fashion/shirts" },
      { _id: 202, label: "Pants", link: "/mens-fashion/pants" },
      { _id: 203, label: "Shoes", link: "/mens-fashion/shoes" },
      { _id: 204, label: "Accessories", link: "/mens-fashion/accessories" },
    ],
  },
  {
    _id: 3,
    label: "Electronics",
    link: "/electronics",
    hasSubmenu: false,
  },
  {
    _id: 4,
    label: "Home & Lifestyle",
    link: "/home-&-lifestyle",
    hasSubmenu: false,
  },
  {
    _id: 5,
    label: "Medicine",
    link: "/medicine",
    hasSubmenu: false,
  },
  {
    _id: 6,
    label: "Sports & Outdoor",
    link: "/sports-&-outdoor",
    hasSubmenu: false,
  },
  {
    _id: 7,
    label: "Baby’s & Toys",
    link: "/babys-&-toys",
    hasSubmenu: false,
  },
  {
    _id: 8,
    label: "Groceries & Pets",
    link: "/groceries-&-pets",
    hasSubmenu: false,
  },
  {
    _id: 9,
    label: "Health & Beauty",
    link: "/health-&-beauty",
    hasSubmenu: false,
  },
];

export const heroSliderData = [
  {
    _id: 1,
    title: "iPhone 14 Series",
    description: "Up to 10% off Voucher",
    image: "/images/hero-slider/img_1.jpeg",
    ctaLink: "/shop-now",
  },
  {
    _id: 2,
    title: "Xbox Consoles",
    description: "Up to 50% on select Xbox games",
    image: "/images/hero-slider/img_2.png",
    ctaLink: "/shop-now",
  },
  {
    _id: 3,
    title: "Apple Watch Ultra 2",
    description: "Sale up to 20% off",
    image: "/images/hero-slider/img_3.png",
    ctaLink: "/shop-now",
  },
  {
    _id: 4,
    title: "Nike, Adidas",
    description: "MIN 40% OFF",
    image: "/images/hero-slider/img_4.png",
    ctaLink: "/shop-now",
  },
  {
    _id: 5,
    title: "Playstation 5",
    description: "MIN 25% OFF",
    image: "/images/hero-slider/img_5.png",
    ctaLink: "/shop-now",
  },
  {
    _id: 6,
    title: "Galaxy S24 | S24+",
    description: "Get up to 5% off",
    image: "/images/hero-slider/img_6.png",
    ctaLink: "/shop-now",
  },
];

/* products data */
export const flashSalesProductsData = [
  {
    _id: "1",
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    original_price: 160,
    discount: "-40%",
    rating: 4.5,
    reviews: 88,
    imageUrl: "/images/product/flash-sales/img_1.png",
  },
  {
    _id: "2",
    name: "AK-900 Wired Keyboard",
    price: 960,
    original_price: 1160,
    discount: "-35%",
    rating: 3.5,
    reviews: 75,
    imageUrl: "/images/product/flash-sales/img_2.png",
  },
  {
    _id: "3",
    name: "IPS LCD Gaming Monitor",
    price: 370,
    original_price: 400,
    discount: "-30%",
    rating: 5,
    reviews: 99,
    imageUrl: "/images/product/flash-sales/img_3.png",
  },
  {
    _id: "4",
    name: "S-Series Comfort Chair",
    price: 375,
    original_price: 400,
    discount: "-25%",
    rating: 4.5,
    reviews: 99,
    imageUrl: "/images/product/flash-sales/img_4.png",
  },
  {
    _id: "5",
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    original_price: 160,
    discount: "-40%",
    rating: 4.5,
    reviews: 88,
    imageUrl: "/images/product/flash-sales/img_1.png",
  },
  {
    _id: "6",
    name: "AK-900 Wired Keyboard",
    price: 960,
    original_price: 1160,
    discount: "-35%",
    rating: 3.5,
    reviews: 75,
    imageUrl: "/images/product/flash-sales/img_2.png",
  },
  {
    _id: "7",
    name: "IPS LCD Gaming Monitor",
    price: 370,
    original_price: 400,
    discount: "-30%",
    rating: 5,
    reviews: 99,
    imageUrl: "/images/product/flash-sales/img_3.png",
  },
  {
    _id: "8",
    name: "S-Series Comfort Chair",
    price: 375,
    original_price: 400,
    discount: "-25%",
    rating: 4.5,
    reviews: 99,
    imageUrl: "/images/product/flash-sales/img_4.png",
  },
];

export const bestSellingProductsData = [
  {
    _id: "1",
    name: "The north coat",
    price: 260,
    original_price: 360,
    rating: 5,
    reviews: 65,
    imageUrl: "/images/product/best-selling/img_1.png",
  },
  {
    _id: "2",
    name: "Gucci duffle bag",
    price: 960,
    original_price: 1160,
    rating: 4.5,
    reviews: 95,
    imageUrl: "/images/product/best-selling/img_2.png",
  },
  {
    _id: "3",
    name: "RGB liquid CPU Cooler",
    price: 160,
    original_price: 170,
    rating: 3.5,
    reviews: 54,
    imageUrl: "/images/product/best-selling/img_3.png",
  },
  {
    _id: "4",
    name: "Small BookSelf",
    price: 360,
    rating: 5,
    reviews: 44,
    imageUrl: "/images/product/best-selling/img_4.png",
  },
  {
    _id: "5",
    name: "The north coat",
    price: 260,
    original_price: 360,
    rating: 5,
    reviews: 65,
    imageUrl: "/images/product/best-selling/img_1.png",
  },
  {
    _id: "6",
    name: "Gucci duffle bag",
    price: 960,
    original_price: 1160,
    rating: 4.5,
    reviews: 95,
    imageUrl: "/images/product/best-selling/img_2.png",
  },
  {
    _id: "7",
    name: "RGB liquid CPU Cooler",
    price: 160,
    original_price: 170,
    rating: 3.5,
    reviews: 54,
    imageUrl: "/images/product/best-selling/img_3.png",
  },
];

export const exploreProductsData = [
  {
    _id: "1",
    name: "Breed Dry Dog Food",
    price: 100,
    // original_price: 360,
    rating: 3,
    reviews: 35,
    imageUrl: "/images/product/explore-products/img_1.jpeg",
  },
  {
    _id: "2",
    name: "CANON EOS DSLR Camera",
    price: 360,
    // original_price: 360,
    rating: 4,
    reviews: 95,
    imageUrl: "/images/product/explore-products/img_2.png",
  },
  {
    _id: "3",
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    // original_price: 360,
    rating: 5,
    reviews: 325,
    imageUrl: "/images/product/explore-products/img_3.png",
  },
  {
    _id: "4",
    name: "Curology Product Set ",
    price: 500,
    // original_price: 360,
    rating: 4,
    reviews: 145,
    imageUrl: "/images/product/explore-products/img_4.png",
  },
  {
    _id: "5",
    name: "Kids Electric Car",
    price: 960,
    // original_price: 360,
    rating: 5,
    reviews: 65,
    imageUrl: "/images/product/explore-products/img_5.png",
    new: true,
  },
  {
    _id: "6",
    name: "Jr. Zoom Soccer Cleats",
    price: 1160,
    // original_price: 360,
    rating: 5,
    reviews: 35,
    imageUrl: "/images/product/explore-products/img_6.png",
  },
  {
    _id: "7",
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    // original_price: 360,
    rating: 4.5,
    reviews: 55,
    imageUrl: "/images/product/explore-products/img_7.png",
    new: true,
  },
  {
    _id: "8",
    name: "Quilted Satin Jacket",
    price: 660,
    // original_price: 360,
    rating: 4.5,
    reviews: 55,
    imageUrl: "/images/product/explore-products/img_8.png",
  },
  {
    _id: "9",
    name: "Breed Dry Dog Food",
    price: 100,
    // original_price: 360,
    rating: 3,
    reviews: 35,
    imageUrl: "/images/product/explore-products/img_1.jpeg",
  },
  {
    _id: "10",
    name: "CANON EOS DSLR Camera",
    price: 360,
    // original_price: 360,
    rating: 4,
    reviews: 95,
    imageUrl: "/images/product/explore-products/img_2.png",
  },
  {
    _id: "11",
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    // original_price: 360,
    rating: 5,
    reviews: 325,
    imageUrl: "/images/product/explore-products/img_3.png",
  },
  {
    _id: "12",
    name: "Curology Product Set ",
    price: 500,
    // original_price: 360,
    rating: 4,
    reviews: 145,
    imageUrl: "/images/product/explore-products/img_4.png",
  },
  {
    _id: "13",
    name: "Kids Electric Car",
    price: 960,
    // original_price: 360,
    rating: 5,
    reviews: 65,
    imageUrl: "/images/product/explore-products/img_5.png",
    new: true,
  },
  {
    _id: "14",
    name: "Jr. Zoom Soccer Cleats",
    price: 1160,
    // original_price: 360,
    rating: 5,
    reviews: 35,
    imageUrl: "/images/product/explore-products/img_6.png",
  },
  {
    _id: "15",
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    // original_price: 360,
    rating: 4.5,
    reviews: 55,
    imageUrl: "/images/product/explore-products/img_7.png",
    new: true,
  },
  {
    _id: "16",
    name: "Quilted Satin Jacket",
    price: 660,
    // original_price: 360,
    rating: 4.5,
    reviews: 55,
    imageUrl: "/images/product/explore-products/img_8.png",
  },
];

/* category slider data */
export const categoriesSliderData = [
  { _id: 1, name: "Phones", icon: CellPhoneIcon },
  { _id: 2, name: "Computers", icon: ComputerIcon },
  { _id: 3, name: "SmartWatch", icon: SmartWatchIcon },
  { _id: 4, name: "Camera", icon: CameraIcon },
  { _id: 5, name: "HeadPhones", icon: HeadphoneIcon },
  { _id: 6, name: "Gaming", icon: GamepadIcon },
  { _id: 7, name: "Phones", icon: CellPhoneIcon },
  { _id: 8, name: "Computers", icon: ComputerIcon },
  { _id: 9, name: "SmartWatch", icon: SmartWatchIcon },
  { _id: 10, name: "Camera", icon: CameraIcon },
  { _id: 11, name: "HeadPhones", icon: HeadphoneIcon },
  { _id: 12, name: "Gaming", icon: GamepadIcon },
];

/* about page data */
export const aboutStatsData = [
  {
    _id: 1,
    value: "10.5k",
    label: "Sellers active on our site",
    icon: ShopIcon,
  },
  {
    _id: 2,
    value: "33k",
    label: "Monthly Product Sale",
    icon: DollarIcon,
  },
  {
    _id: 3,
    value: "45.5k",
    label: "Customers active on our site",
    icon: ShoppingBagIcon,
  },
  {
    _id: 4,
    value: "25k",
    label: "Annual gross sale on our site",
    icon: MoneyBagIcon,
  },
];

export const aboutSliderData = [
  {
    _id: 1,
    name: "Tom Cruise",
    position: "Founder & Chairman",
    image: "/images/about/slider/img_1.png",
    socialLinks: {
      twitter: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    _id: 2,
    name: "Emma Watson",
    position: "Managing Director",
    image: "/images/about/slider/img_2.png",
    socialLinks: {
      twitter: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    _id: 3,
    name: "Will Smith",
    position: "Product Designer",
    image: "/images/about/slider/img_3.png",
    socialLinks: {
      twitter: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    _id: 4,
    name: "Tom Cruise",
    position: "Founder & Chairman",
    image: "/images/about/slider/img_1.png",
    socialLinks: {
      twitter: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    _id: 5,
    name: "Emma Watson",
    position: "Managing Director",
    image: "/images/about/slider/img_2.png",
    socialLinks: {
      twitter: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    _id: 6,
    name: "Will Smith",
    position: "Product Designer",
    image: "/images/about/slider/img_3.png",
    socialLinks: {
      twitter: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
];

/* new arrival data */
export const newArrivalData = [
  {
    id: 1,
    title: "PlayStation 5",
    description: "Black and White version of the PS5 coming out on sale.",
    image: "ps5.jpg",
    link: "#",
    style: "col-span-1 row-span-2 bg-black",
  },
  {
    id: 2,
    title: "Women's Collections",
    description: "Featured women's collections that give you another vibe.",
    image: "women-collection.jpg",
    link: "#",
    style: "col-span-1 bg-gray-900",
  },
  {
    id: 3,
    title: "Speakers",
    description: "Amazon wireless speakers.",
    image: "speakers.jpg",
    link: "#",
    style: "col-span-1 bg-gray-800",
  },
  {
    id: 4,
    title: "Perfume",
    description: "GUCCI INTENSE OUD EDP",
    image: "perfume.jpg",
    link: "#",
    style: "col-span-1 bg-gray-800",
  },
];

/* services data */
export const serviceFeatures = [
  {
    _id: 1,
    title: "FREE AND FAST DELIVERY",
    description: "Free delivery for all orders over $140",
    icon: DeliveryIcon,
  },
  {
    _id: 2,
    title: "24/7 CUSTOMER SERVICE",
    description: "Friendly 24/7 customer support",
    icon: CustomerServiceIcon,
  },
  {
    _id: 3,
    title: "MONEY BACK GUARANTEE",
    description: "We return money within 30 days",
    icon: SecureIcon,
  },
];
